-- PRIMARY KEY
ALTER TABLE BUSINESS
ADD CONSTRAINT PK_BUSINESS PRIMARY KEY ("business_id");

ALTER TABLE CATEGORY
ADD CONSTRAINT PK_CATEGORY PRIMARY KEY ("category_id");

ALTER TABLE BUSINESS_CATEGORY
ADD CONSTRAINT PK_BUSINESS_CATEGORY PRIMARY KEY ("business_id","category_id");

ALTER TABLE ACCESSIBILITY
ADD CONSTRAINT PK_ACCESSIBILITY PRIMARY KEY ("accessibility_id");

ALTER TABLE SERVICE
ADD CONSTRAINT PK_SERVICE PRIMARY KEY ("service_id");

ALTER TABLE RESTAURANT
ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY ("restaurant_id");

ALTER TABLE ELITE
ADD CONSTRAINT PK_ELITE PRIMARY KEY ("user_id","year");

ALTER TABLE REVIEW
ADD CONSTRAINT PK_REVIEW PRIMARY KEY ("review_id");

-- Table de fait TENDENCY
ALTER TABLE TENDENCY
ADD CONSTRAINT PK_ELITE PRIMARY KEY ("business_id","accessibility_id","service_id","restaurant_id");

-- FOREIGN KEY
-- Table BUSINESS_CATEGORY
ALTER TABLE BUSINESS_CATEGORY
ADD CONSTRAINT FK1_BUSINESS_CATEGORY FOREIGN KEY ("business_id") REFERENCES BUSINESS ("business_id");

ALTER TABLE BUSINESS_CATEGORY
ADD CONSTRAINT FK2_BUSINESS_CATEGORY FOREIGN KEY ("category_id") REFERENCES CATEGORY ("category_id");

-- Table REVIEW
ALTER TABLE REVIEW
ADD CONSTRAINT FK1_REVIEW FOREIGN KEY ("business_id") REFERENCES BUSINESS ("business_id");

ALTER TABLE REVIEW
ADD CONSTRAINT FK2_REVIEW FOREIGN KEY ("user_id") REFERENCES ELITE ("user_id");

-- Table de fait TENDENCY

ALTER TABLE TENDENCY
ADD CONSTRAINT FK1_TENDENCY FOREIGN KEY ("business_id") REFERENCES BUSINESS ("business_id");

ALTER TABLE TENDENCY
ADD CONSTRAINT FK2_TENDENCY FOREIGN KEY ("accessibility_id") REFERENCES ACCESSIBILITY ("accessibility_id");

ALTER TABLE TENDENCY
ADD CONSTRAINT FK3_TENDENCY FOREIGN KEY ("restaurant_id") REFERENCES RESTAURANT ("restaurant_id");

ALTER TABLE TENDENCY
ADD CONSTRAINT FK4_TENDENCY FOREIGN KEY ("service_id") REFERENCES SERVICE ("service_id");

ALTER TABLE TENDENCY
ADD CONSTRAINT FK5_TENDENCY FOREIGN KEY ("review_id") REFERENCES REVIEW ("review_id");

-- INDEX SUR LES FK
-- Table BUSINESS_CATEGORY

CREATE INDEX I_FK1_BUSINESS_CATEGORY
ON BUSINESS_CATEGORY ("business_id");

CREATE INDEX I_FK2_BUSINESS_CATEGORY
ON BUSINESS_CATEGORY ("category_id");

-- Table REVIEW

CREATE INDEX I_FK1_REVIEW
ON REVIEW ("business_id");

CREATE INDEX I_FK2_REVIEW
ON REVIEW ("user_id");

-- Table de fait TENDENCY

CREATE INDEX I_FK1_TENDENCY
ON REVIEW ("business_id");

CREATE INDEX I_FK2_TENDENCY
ON REVIEW ("accessibility_id");

CREATE INDEX I_FK3_TENDENCY
ON REVIEW ("restaurant_id");

CREATE INDEX I_FK4_TENDENCY
ON REVIEW ("service_id");

CREATE INDEX I_FK5_TENDENCY
ON REVIEW ("review_id");